# Generated by Django 3.2.3 on 2021-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='candidate_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
