# Generated by Django 3.2.3 on 2021-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210823_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='candidate_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
